// <auto-generated />
namespace plan2plan.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class plan2plan_4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(plan2plan_4));
        
        string IMigrationMetadata.Id
        {
            get { return "201803221554179_plan2plan_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
